# Generated by Django 3.1.1 on 2020-10-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Spice', models.IntegerField(choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('HOT', 'Hot')])),
                ('Veg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.IntegerField(choices=[(9, 'Small'), (11, 'Medium'), (13, 'Large'), (17, 'Family')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('toppings', models.ManyToManyField(to='create.Toppings')),
            ],
        ),
    ]
