# Generated by Django 3.1.1 on 2020-10-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='Spice',
            field=models.TextField(choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('HOT', 'Hot')]),
        ),
    ]
